---
title: "Initial Korean covid 19"
author: "Chris Gonzalez"
date: "June 21,2023"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?

## Methods 
The present study aims to conduct an analysis of patients, taking into consideration the variable factor of Sex and its result factor variable. To facilitate the examination of the data and initiate the analysis, a graphical representation will be generated using the ggplot package. Additionally, both numerical and inferential techniques will be employed to further explore and interpret the findings. This will help determine if sex had any impact in the decease. 



## Graphical results - use ggplot commands to do this  



  





  
## Numerical results






## Inferential results 






## Conclusions

